dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4.1
bundler_args: --path $HOME/.bundle
cache:
  directories:
    - $HOME/.phantomjs
    - $HOME/.bundle
env:
  global:
    - DATABASE_URL=mysql2://root:travis@127.0.0.1:3306/wca_test
    - RACK_ENV=test
before_install:
  - cd WcaOnRails/
before_script:
  - bundle exec rake db:reset
script:
  - bundle exec pre-commit run git
  - bundle exec rubocop
  - bundle exec rake
