dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4.1
bundler_args: --path $HOME/.bundle
cache:
  directories:
    - $HOME/.phantomjs
    - $HOME/.bundle
    - WcaOnRails/node_modules
  yarn: true
env:
  global:
    - DATABASE_URL=mysql2://root:travis@127.0.0.1:3306/wca_test
    - RACK_ENV=test
before_install:
  - nvm install 6.9.1
  - nvm use 6.9.1

  # From https://yarnpkg.com/en/docs/install-ci#travis-tab
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

  - cd WcaOnRails/
before_script:
  # Wait for mysql to fully come up before continuing.
  # See https://github.com/thewca/worldcubeassociation.org/issues/1629
  - /usr/sbin/mysql-5.6-wait-ready

  - bundle exec rake db:reset
  - bundle exec rake assets:precompile
  - bin/webpack-dev-server &
script:
  - bundle exec pre-commit run git
  - bundle exec rubocop
  - bundle exec rake
